import './globals.css'
import { amazonEmberFont } from '@/utils/Fonts';
import Head from "next/head";
import favIcon from '../../public/images/amazon.png'



export const metadata = {
  title: "Amazon.com. Spend less. Smile more.",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: favIcon.src }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={amazonEmberFont.className}>{children}</body>
    </html>
  );
}
